### ISSUE TITLE
Gradle [Forge 1.7.10] Build Failed

### ISSUE THREAD

**Issue by michaelproeber** [MinecraftForge/ForgeGradle#138]
Downloaded forge src 1.7.10 10.13.0.1180 and ran gradle; build failed. here's the log.
22:26:59.231 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 59.343 secs
22:26:59.256 [LIFECYCLE] [org.gradle.api.Project] ****************************
22:26:59.266 [LIFECYCLE] [org.gradle.api.Project]  Powered By MCP:  
22:26:59.275 [LIFECYCLE] [org.gradle.api.Project]  http://mcp.ocean-labs.de/  
22:26:59.284 [LIFECYCLE] [org.gradle.api.Project]  Searge, ProfMobius, Fesh0r,
22:26:59.294 [LIFECYCLE] [org.gradle.api.Project]  R4wk, ZeuX, IngisKahn  
22:26:59.304 [INFO] [org.gradle.api.Project] Resolving:  MCP Data version : {MCP_VERSION}
22:26:59.369 [ERROR] [org.gradle.configuration.project.LifecycleProjectEvaluator] Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
org.gradle.api.ProjectConfigurationException: You must set the Minecraft Version!
    at net.minecraftforge.gradle.user.patch.UserPatchExtension.getApiVersion(UserPatchExtension.java:64)
    at net.minecraftforge.gradle.user.patch.UserPatchExtension_Decorated.getApiVersion(Unknown Source)
    at net.minecraftforge.gradle.user.patch.UserPatchBasePlugin.getApiVersion(UserPatchBasePlugin.java:233)
    at net.minecraftforge.gradle.user.patch.UserPatchBasePlugin.getApiVersion(UserPatchBasePlugin.java:26)
    at net.minecraftforge.gradle.user.UserBasePlugin.resolve(UserBasePlugin.java:244)
    at net.minecraftforge.gradle.user.UserBasePlugin.resolve(UserBasePlugin.java:75)
    at net.minecraftforge.gradle.delayed.DelayedBase.resolve(DelayedBase.java:73)
    at net.minecraftforge.gradle.delayed.DelayedString.call(DelayedString.java:24)
    at net.minecraftforge.gradle.common.BasePlugin.afterEvaluate(BasePlugin.java:151)
    at net.minecraftforge.gradle.user.UserBasePlugin.afterEvaluate(UserBasePlugin.java:951)
    at net.minecraftforge.gradle.common.BasePlugin$2.execute(BasePlugin.java:102)
    at net.minecraftforge.gradle.common.BasePlugin$2.execute(BasePlugin.java:98)
    at org.gradle.listener.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:109)
    at org.gradle.listener.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:98)
    at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
    at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy13.afterEvaluate(Unknown Source)
    at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
    at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
    at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:470)
    at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:79)
    at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:31)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:128)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:105)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:85)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:81)
    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:39)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:29)
    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
    at org.gradle.launcher.Main.doAction(Main.java:33)
    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
    at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
    at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
Caused by: java.lang.NullPointerException
    ... 57 more
22:26:59.472 [ERROR] [org.gradle.BuildExceptionReporter] 
22:26:59.479 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
22:26:59.490 [ERROR] [org.gradle.BuildExceptionReporter] 
22:26:59.498 [ERROR] [org.gradle.BuildExceptionReporter] \* Where:
22:26:59.524 [ERROR] [org.gradle.BuildExceptionReporter] Build file 'C:\Users\redacted\Downloads\forge-1.7.10-10.13.0.1180-src\build.gradle' line: 18
22:26:59.532 [ERROR] [org.gradle.BuildExceptionReporter] 
22:26:59.541 [ERROR] [org.gradle.BuildExceptionReporter] \* What went wrong:
22:26:59.548 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating root project 'forge-1.7.10-10.13.0.1180-src'.
22:26:59.557 [ERROR] [org.gradle.BuildExceptionReporter] > Could not generate a proxy class for class net.minecraftforge.gradle.tasks.GenSrgTask.
22:26:59.567 [ERROR] [org.gradle.BuildExceptionReporter] 
22:26:59.578 [ERROR] [org.gradle.BuildExceptionReporter] \* Try:
22:26:59.587 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
22:26:59.599 [LIFECYCLE] [org.gradle.BuildResultLogger] 
22:26:59.621 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
22:26:59.629 [LIFECYCLE] [org.gradle.BuildResultLogger] 
22:26:59.667 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 1 mins 9.493 secs

**Comment by Leetfox** [comment]
Had same issue on Windows 8- I installed Eclipse and Forge in the Program Files x86 folder. The installing script didn't have the right permission in that folder, so after creating a seperate folder and installing Eclipse and Forge in that folder I was able to install successfully. Hopefully will help someone
