### ISSUE TITLE
[FG 1.2] Execution failed for task retroMapClean

### ISSUE THREAD

**Issue by iLexiconn** [MinecraftForge/ForgeGradle#232]
Stacktrace:

```java
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at net.minecraftforge.srg2source.rangeapplier.RangeMap.read(RangeMap.java:100)
        at net.minecraftforge.srg2source.rangeapplier.RangeApplier.remapSources(RangeApplier.java:203)
        at net.minecraftforge.gradle.tasks.ApplyS2STask.applyRangeMap(ApplyS2STask.java:141)
        at net.minecraftforge.gradle.tasks.ApplyS2STask.doTask(ApplyS2STask.java:94)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 58 more
```

**Comment by LexManos** [comment]
Somehow your cache got currupt clean and try again.

**Comment by iLexiconn** [comment]
Thanks, it works now.
