### ISSUE TITLE
Jenkins build STILL failing: SignJar is failing now

### ISSUE THREAD

**Issue by cpw** [MinecraftForge/ForgeGradle#242]
OK, And we lurch forward to ANOTHER issue on jenkins. The signjar task isn't working.

```
Starting process 'command '/usr/lib/jvm/java-7-openjdk-amd64/bin/java''. Working directory: /home/jenkinsmount/jenkins_slave/workspace/minecraftforge Command: /usr/lib/jvm/java-7-openjdk-amd64/bin/java -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/launch4j.jar:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/launch4j.xml:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/w32api/libshell32.a:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/w32api/libkernel32.a:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/w32api/crt2.o:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/w32api/MinGW.LICENSE.txt:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/w32api/libuser32.a:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/w32api/libmsvcrt.a:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/w32api/libadvapi32.a:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/w32api/libgcc.a:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/w32api/libmingw32.a:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/head/LICENSE.txt:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/head/head.o:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/head/consolehead.o:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/head/guihead.o:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/lib/formsrt.jar:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/lib/jgoodies-common.jar:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/lib/commons-logging.jar:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/lib/JGoodies.Forms.LICENSE.txt:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/lib/foxtrot.jar:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/lib/foxtrot.LICENSE.txt:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/lib/commons.LICENSE.txt:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/lib/Nuvola.Icon.Theme.LICENSE.txt:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/lib/ant.LICENSE.txt:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/lib/JGoodies.Looks.LICENSE.txt:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/lib/ant.jar:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/lib/commons-beanutils.jar:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/lib/XStream.LICENSE.txt:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/lib/jgoodies-forms.jar:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/lib/jgoodies-looks.jar:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/lib/xstream.jar:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/bin/windres:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/bin/COPYING:/home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/bin/ld net.sf.launch4j.Main /home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/launch4j/launch4j.xml
Successfully started process 'command '/usr/lib/jvm/java-7-openjdk-amd64/bin/java''
launch4j: Compiling resources
launch4j: Linking
launch4j: Wrapping
launch4j: Successfully created /home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/distributions/forge-1.8-11.14.3.1509-installer-win.exe
:createExe (Thread[main,5,main]) completed. Took 0.294 secs.
:launch4j (Thread[main,5,main]) started.
:launch4j
Skipping task ':launch4j' as it has no actions.
:launch4j (Thread[main,5,main]) completed. Took 0.0 secs.
:signUniversal (Thread[main,5,main]) started.
:signUniversal
Executing task ':signUniversal' (up-to-date check took 0.001 secs) due to:
  No history is available.

[ant:signjar] Signing JAR: /home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/tmp/signUniversal/forge-1.8-11.14.3.1509-universal.jar.unsigned.tmp to /home/jenkinsmount/jenkins_slave/workspace/minecraftforge/build/tmp/signUniversal/forge-1.8-11.14.3.1509-universal.jar.signed.tmp as forge
[ant:signjar] jarsigner error: java.lang.NullPointerException

:signUniversal FAILED
:signUniversal (Thread[main,5,main]) completed. Took 1.457 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':signUniversal'.
> jarsigner returned: 1

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':signUniversal'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: : jarsigner returned: 1
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:643)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
	at org.apache.tools.ant.taskdefs.SignJar.signOneJar(SignJar.java:488)
	at org.apache.tools.ant.taskdefs.SignJar.execute(SignJar.java:365)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:77)
	at org.gradle.api.internal.project.ant.BasicAntBuilder.doInvokeMethod(BasicAntBuilder.java:92)
	at net.minecraftforge.gradle.tasks.SignJar.doTask(SignJar.java:65)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:589)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:572)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 49 more


BUILD FAILED

Total time: 4 mins 23.555 secs
Build step 'Invoke Gradle script' changed build result to FAILURE
Build step 'Invoke Gradle script' marked build as failure

Build step 'Groovy Postbuild' marked build as failure
MCPForge is disabled. Triggering skipped
Finished: FAILURE
```

The jarsigner section is being fed through init.gradle, correctly as far as I can tell.. Clearly, again, this used to work, but I'm not sure how it was done prior to gradle 2.0 (I used to do it using an ant task, back in the day, and it LOOKS like the ant task you're using in the SignJar code is the same, but I can't be certain).

**Comment by cpw** [comment]
Observations: the files in the tmp dir are empty jar/zip files, both of them (unsigned and signed). I suspect it's trying to sign an empty jar and failing as a result. I'd need to try using an alternative method for signing to verify...

**Comment by LexManos** [comment]
Fixed https://github.com/MinecraftForge/ForgeGradle/commit/062d89f337553b2ab9847327b678850627ea73a8
