### ISSUE TITLE
Patcher plugin broken with Gradle 2.10

### ISSUE THREAD

**Issue by matthewprenger** [MinecraftForge/ForgeGradle#323]
Error when trying to build Forge (master):
```
Parallel execution with configuration on demand is an incubating feature.
This set of MCP mappings was designed for MC 1.8.8. Use at your own peril.
:combineResources UP-TO-DATE
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:genGradleProjects UP-TO-DATE
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:deobfuscateJar UP-TO-DATE
:decompileJar UP-TO-DATE
:sourceProcessJar UP-TO-DATE
:patchForgeJar UP-TO-DATE
:remapForgeJar UP-TO-DATE
:extractForgeResources UP-TO-DATE
:extractForgeSources UP-TO-DATE
:setupProjectForge UP-TO-DATE
:makeJarForge
------------------------ 
--------SUB-CALL-------- 
------------------------ 
Parallel execution with configuration on demand is an incubating feature.
:Forge:compileJava UP-TO-DATE
:Forge:processResources UP-TO-DATE
:Forge:classes UP-TO-DATE
:Forge:jar UP-TO-DATE

BUILD SUCCESSFUL

Total time: 0.631 secs
------------------------ 
------END-SUB-CALL------ 
------------------------ 
:setupProjects UP-TO-DATE
:reobfuscate UP-TO-DATE
:extractNonMcClasses UP-TO-DATE
:extractExcForge UP-TO-DATE
:extractForgeRangemap UP-TO-DATE
:retromapMcForge UP-TO-DATE
:retromapNonMcForge UP-TO-DATE
:extractNonMcSources UP-TO-DATE
:genBinaryPatches UP-TO-DATE
:mergeFiles UP-TO-DATE
:genUserdevPatches UP-TO-DATE
:packagedUserdevPatches UP-TO-DATE
:buildUserdev
:changelog SKIPPED
:downloadInstaller UP-TO-DATE
:compressDeobf SKIPPED
:crowdin
Crowdin api key is null, skipping task.
:crowdin SKIPPED
:processJson
:outputJar

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task 'outputJar' during up-to-date check.  See stacktrace for details.
> java.io.FileNotFoundException: ady$FlowerEntry.class (No such file or directory)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.UncheckedIOException: Failed to capture snapshot of input files for task 'outputJar' during up-to-date check.  See stacktrace for details.
	at org.gradle.api.internal.changedetection.rules.TaskUpToDateState.<init>(TaskUpToDateState.java:60)
	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:132)
	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.afterTask(DefaultTaskArtifactStateRepository.java:123)
	at org.gradle.api.internal.changedetection.changes.ShortCircuitTaskArtifactStateRepository$RerunTaskArtifactState.afterTask(ShortCircuitTaskArtifactStateRepository.java:89)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: ady$FlowerEntry.class (No such file or directory)
	at org.gradle.internal.hash.HashUtil.createHash(HashUtil.java:39)
	at org.gradle.api.internal.hash.DefaultHasher.hash(DefaultHasher.java:24)
	at org.gradle.api.internal.changedetection.state.CachingFileSnapshotter.snapshot(CachingFileSnapshotter.java:57)
	at org.gradle.api.internal.changedetection.state.CachingFileSnapshotter.snapshot(CachingFileSnapshotter.java:46)
	at org.gradle.api.internal.changedetection.state.CachingFileSnapshotter.snapshot(CachingFileSnapshotter.java:29)
	at org.gradle.api.internal.changedetection.state.DefaultFileCollectionSnapshotter$1.run(DefaultFileCollectionSnapshotter.java:70)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:192)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:175)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:106)
	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:187)
	at org.gradle.api.internal.changedetection.state.DefaultTaskArtifactStateCacheAccess.useCache(DefaultTaskArtifactStateCacheAccess.java:60)
	at org.gradle.api.internal.changedetection.state.DefaultFileCollectionSnapshotter.snapshot(DefaultFileCollectionSnapshotter.java:62)
	at org.gradle.api.internal.changedetection.rules.TaskUpToDateState.<init>(TaskUpToDateState.java:56)
	... 18 more
Caused by: java.io.FileNotFoundException: ady$FlowerEntry.class (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.gradle.internal.hash.HashUtil.createHash(HashUtil.java:34)
	... 31 more


BUILD FAILED

Total time: 4.317 secs
```

**Comment by matthewprenger** [comment]
Seems to work now, not sure what fixed it.
