### ISSUE TITLE
Decompile runs out ram

### ISSUE THREAD

**Issue by Dijkstra1** [MinecraftForge/ForgeGradle#327]
I trying to setup forge 1.8.9, I run "gradlew setupForge", and when it gets to decompile it gives me this:
* What went wrong:
Execution failed for task ':decompileJar'.
> Java heap space

How to do I overcome this, I did not have this problem with 1.7.10

Full stacktrace:

This set of MCP mappings was designed for MC 1.8.8. Use at your own peril.
#################################################
         ForgeGradle 2.1-SNAPSHOT-8e42161
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP unknown
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################
:getVersionJson
:getAssetIndex UP-TO-DATE
:getAssets
Current status: 29/734   3%
Current status: 63/734   8%
Current status: 100/734   13%
Current status: 127/734   17%
Current status: 184/734   25%
Current status: 243/734   33%
Current status: 275/734   37%
Current status: 283/734   38%
Current status: 314/734   42%
Current status: 354/734   48%
Current status: 384/734   52%
Current status: 392/734   53%
Current status: 424/734   57%
Current status: 461/734   62%
Current status: 478/734   65%
Current status: 483/734   65%
Current status: 511/734   69%
Current status: 544/734   74%
Current status: 560/734   76%
Current status: 583/734   79%
Current status: 611/734   83%
Current status: 644/734   87%
Current status: 669/734   91%
Current status: 679/734   92%
Current status: 715/734   97%
Current status: 728/734   99%
:makeForgeStart
:genGradleProjects UP-TO-DATE
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:deobfuscateJar UP-TO-DATE
:decompileJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':decompileJar'.
> Java heap space

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':decompileJar'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAc
java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(E
)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.ex
ecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(Ski
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(Valid
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.exe
uter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execut
ava:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipO
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execut
ava:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorke
r.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorke
r.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.p
or.java:62)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.r
50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPl
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskG
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecuti
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.ja
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.jav
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecution
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildO
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildO
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleL
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLaun
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLaunch
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLaunch
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildO
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildO
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLaunche
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.ja
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController
.java:94)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBui
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRu
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuild
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuild
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBui
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBui
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(Da
cuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(Da
cuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute
7)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute
0)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValid
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValid
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(Command
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(Command
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingA
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingA
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.ja
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at org.jetbrains.java.decompiler.util.DataInputFullStream.<init>(DataInputFullS
        at org.jetbrains.java.decompiler.struct.attr.StructGeneralAttribute.stream(Stru
        at org.jetbrains.java.decompiler.struct.attr.StructLineNumberTableAttribute.ini
ribute.java:37)
        at org.jetbrains.java.decompiler.struct.StructMember.readAttribute(StructMember
        at org.jetbrains.java.decompiler.struct.StructMethod.readAttribute(StructMethod
        at org.jetbrains.java.decompiler.struct.StructMember.readAttributes(StructMembe
        at org.jetbrains.java.decompiler.struct.StructMethod.readAttribute(StructMethod
        at org.jetbrains.java.decompiler.struct.StructMember.readAttributes(StructMembe
        at org.jetbrains.java.decompiler.struct.StructMethod.<init>(StructMethod.java:7
        at org.jetbrains.java.decompiler.struct.StructClass.<init>(StructClass.java:116
        at org.jetbrains.java.decompiler.struct.StructClass.<init>(StructClass.java:75)
        at org.jetbrains.java.decompiler.struct.StructContext.addArchive(StructContext.
        at org.jetbrains.java.decompiler.struct.StructContext.addSpace(StructContext.ja
        at org.jetbrains.java.decompiler.struct.StructContext.addSpace(StructContext.ja
        at org.jetbrains.java.decompiler.main.Fernflower.addAllClasspath(Fernflower.jav
        at org.jetbrains.java.decompiler.main.Fernflower.<init>(Fernflower.java:48)
        at org.jetbrains.java.decompiler.main.decompiler.BaseDecompiler.<init>(BaseDeco
        at net.minecraftforge.gradle.tasks.ApplyFernFlowerTask.applyFernFlower(ApplyFer
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$
tationProcessingTaskFactory.java:226)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$
tionProcessingTaskFactory.java:219)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$
tionProcessingTaskFactory.java:208)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAc
ava:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAc
java:61)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(E
)

BUILD FAILED

Total time: 2 mins 42.262 secs

**Comment by Cazzar** [comment]
Refer to #324
