### ISSUE TITLE
decompileMc runs for over 6 minutes and fails

### ISSUE THREAD

**Issue by Hemmels** [MinecraftForge/ForgeGradle#383]
I have a decent processor and 16Gb RAM running a 64-bit Java 8 JDK.
At my default 2Gb-heap/eclipse/gradle setupDecompWorkspace run configuration, it stuck at 44%, and then eventually threw a out of memory exception when running decompileMc - specifically:

Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.lang.String.split(String.java:2380)
	at java.lang.String.split(String.java:2422)
	at org.jetbrains.java.decompiler.struct.consts.LinkConstant.resolveDescriptor(LinkConstant.java:139)
	at org.jetbrains.java.decompiler.struct.consts.LinkConstant.initConstant(LinkConstant.java:130)
	at org.jetbrains.java.decompiler.struct.consts.LinkConstant.resolveConstant(LinkConstant.java:94)
	at org.jetbrains.java.decompiler.struct.consts.ConstantPool.<init>(ConstantPool.java:102)
	at org.jetbrains.java.decompiler.struct.StructClass.<init>(StructClass.java:87)
	at org.jetbrains.java.decompiler.struct.StructClass.<init>(StructClass.java:75)
	at org.jetbrains.java.decompiler.struct.StructContext.addArchive(StructContext.java:167)
	at org.jetbrains.java.decompiler.struct.StructContext.addSpace(StructContext.java:100)
	at org.jetbrains.java.decompiler.struct.StructContext.addSpace(StructContext.java:78)
	at org.jetbrains.java.decompiler.main.decompiler.BaseDecompiler.addSpace(BaseDecompiler.java:36)
	at net.minecraftforge.gradle.tasks.ApplyFernFlowerTask.applyFernFlower(ApplyFernFlowerTask.java:98)

I also tried with a 4Gb heap, but it has been running for over 10minutes before failing:

Caused by: java.io.StreamCorruptedException: invalid stream header: 02ACED00
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:808)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:301)
	at org.gradle.internal.io.ClassLoaderObjectInputStream.<init>(ClassLoaderObjectInputStream.java:27)
	at org.gradle.internal.serialize.Message$ExceptionReplacingObjectInputStream.<init>(Message.java:208)

**Comment by TehNut** [comment]
#324

**Comment by Hemmels** [comment]
Nevermind. 
Confirmed working with 4Gb heap and:

minecraft {
    version = "1.10.2-12.18.1.2075"
    mappings = 'snapshot_20160830'
}
