### ISSUE TITLE
Offline build failed due to realms:1.10.19 dependency - temporary issue?

### ISSUE THREAD

**Issue by radfast** [MinecraftForge/ForgeGradle#475]
This last week, a couple of times the build process has failed with the error message 

>    Could not resolve all dependencies for configuration ':forgeGradleMcDeps'.
    > Could not resolve com.mojang:realms:1.10.19

Building again a couple of days later the exact same build has succeeded **without me changing anything**.  I was building with the ```--offline``` flag both times, using a workspace which I have been using to build successfully hundreds of times.

I should explain that this is a fully automated build process through our Jenkins, and we did not change the Jenkins configuration or workspace at all between the two builds.  So: our build 137 succeeded, build 138 failed with the realms dependency unresolved, build 139 succeeded.  I have the console output archived by the Jenkins if it's needed - see below.

I don't understand how ForgeGradle can be refreshing the minecraft dependencies or deciding "for the first time" that it needs realms1.10.19 as a dependency - if it is in offline mode?!

Maybe this isn't an issue and didn't need reporting, but I wanted to let you guys know.  If ForgeGradle needs to be able to access Mojang's Realms server during the build process every time (even in offline mode) that seems to me to be a problem.  Mojang's Realms server might be down.  I might be trying to build in a train, an airplane or an underground dungeon somewhere with no Wifi...

<details>
<summary>EXPAND TO SEE THE CONSOLE OUTPUT</summary>

    ./gradlew build packCoreJarDev packPlanetsJarDev packMicCoreJarDev packApi cleanOldJarDev --stacktrace --offline
    This mapping 'snapshot_20171003' was designed for MC 1.12! Use at your own peril.
    #################################################
             ForgeGradle 2.3-SNAPSHOT-315a0db        
      https://github.com/MinecraftForge/ForgeGradle  
    #################################################
                   Powered by MCP unknown               
                 http://modcoderpack.com             
             by: Searge, ProfMobius, Fesh0r,         
             R4wk, ZeuX, IngisKahn, bspkrs           
    #################################################
    Found AccessTransformer: micdoodlecore_at.cfg
    :deobfCompileDummyTask
    :getVersionJson
    :extractUserdev UP-TO-DATE
    :downloadClient SKIPPED
    :downloadServer SKIPPED
    :splitServerJar SKIPPED
    :mergeJars SKIPPED
    :applyBinaryPatches SKIPPED
    :deobfProvidedDummyTask
    :extractDependencyATs SKIPPED
    :extractMcpData SKIPPED
    :extractMcpMappings SKIPPED
    :genSrgs SKIPPED
    :deobfMcMCP SKIPPED
    :sourceApiJava UP-TO-DATE
    :compileApiJava UP-TO-DATE
    :processApiResources UP-TO-DATE
    :apiClasses UP-TO-DATE
    :sourceMainJava UP-TO-DATE
    :compileJava
    FAILURE: Build failed with an exception.

    * What went wrong:
    Could not resolve all dependencies for configuration ':forgeGradleMcDeps'.
    > Could not resolve com.mojang:realms:1.10.19.
      Required by:
          micdoodle8.mods.galacticraft:Forge:1.12.2-4.0.1.138
       > No cached version of com.mojang:realms:1.10.19 available for offline mode.
       > No cached version of com.mojang:realms:1.10.19 available for offline mode.
       > No cached version of com.mojang:realms:1.10.19 available for offline mode.

    * Try:
    Run with --info or --debug option to get more log output.

    * Exception is:
    org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':forgeGradleMcDeps'.
    	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.rethrowFailure(DefaultLenientConfiguration.java:62)
    	at org.gradle.api.internal.artifacts.ivyservice.DefaultResolvedConfiguration.rethrowFailure(DefaultResolvedConfiguration.java:36)
    	at org.gradle.api.internal.artifacts.ivyservice.SelfResolvingDependencyConfigurationResolver$FilesAggregatingResolvedConfiguration.rethrowFailure(SelfResolvingDependencyConfigurationResolver.java:112)
    	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolvedConfiguration.rethrowFailure(ErrorHandlingConfigurationResolver.java:189)
    	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:644)
    	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:280)
    	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
    	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileTreeConverter.convertInto(DefaultFileCollectionResolveContext.java:194)
    	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:106)
    	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileTrees(DefaultFileCollectionResolveContext.java:78)
    	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileTreeConverter.convertInto(DefaultFileCollectionResolveContext.java:185)
    	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:101)
    	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileTrees(DefaultFileCollectionResolveContext.java:78)
    	at org.gradle.api.internal.file.CompositeFileCollection$1.resolve(CompositeFileCollection.java:88)
    	at org.gradle.api.internal.file.CompositeFileCollection.getSourceCollections(CompositeFileCollection.java:143)
    	at org.gradle.api.internal.file.CompositeFileTree.getSourceCollections(CompositeFileTree.java:31)
    	at org.gradle.api.internal.file.CompositeFileCollection.getFiles(CompositeFileCollection.java:38)
    	at org.gradle.api.internal.changedetection.state.DefaultFileCollectionSnapshotter.snapshot(DefaultFileCollectionSnapshotter.java:47)
    	at org.gradle.api.internal.changedetection.rules.TaskUpToDateState.<init>(TaskUpToDateState.java:55)
    	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:126)
    	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(DefaultTaskArtifactStateRepository.java:69)
    	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:52)
    	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
    	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
    	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
    	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
    	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
    	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
    	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
    	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
    	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
    	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
    	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
    	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
    	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
    	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
    	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:155)
    	at org.gradle.internal.Factories$1.create(Factories.java:22)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
    	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:152)
    	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:33)
    	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:100)
    	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:94)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
    	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:94)
    	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
    	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
    	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
    	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
    	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
    	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
    	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
    	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
    	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
    	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
    	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
    	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
    	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
    	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
    	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
    	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
    	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
    	at org.gradle.launcher.Main.doAction(Main.java:33)
    	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
    	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
    	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
    	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
    	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
    	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
    	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
    Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.mojang:realms:1.10.19.
    Required by:
        micdoodle8.mods.galacticraft:Forge:1.12.2-4.0.1.138
    	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolveModule(RepositoryChainComponentMetaDataResolver.java:83)
    	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolve(RepositoryChainComponentMetaDataResolver.java:59)
    	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.ComponentResolversChain$ComponentMetaDataResolverChain.resolve(ComponentResolversChain.java:80)
    	at org.gradle.api.internal.artifacts.ivyservice.clientmodule.ClientModuleResolver.resolve(ClientModuleResolver.java:44)
    	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$ModuleVersionResolveState.resolve(DependencyGraphBuilder.java:560)
    	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$ModuleVersionResolveState.getMetaData(DependencyGraphBuilder.java:570)
    	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$DependencyEdge.calculateTargetConfigurations(DependencyGraphBuilder.java:256)
    	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$DependencyEdge.attachToTargetConfigurations(DependencyGraphBuilder.java:230)
    	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:137)
    	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:75)
    	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver$1.execute(DefaultArtifactDependencyResolver.java:90)
    	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver$1.execute(DefaultArtifactDependencyResolver.java:80)
    	at org.gradle.internal.Transformers$4.transform(Transformers.java:137)
    	at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:61)
    	at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:39)
    	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:80)
    	at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver$1.run(CacheLockingArtifactDependencyResolver.java:41)
    	at org.gradle.internal.Factories$1.create(Factories.java:22)
    	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:192)
    	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:175)
    	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:106)
    	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:187)
    	at org.gradle.api.internal.artifacts.ivyservice.DefaultCacheLockingManager.useCache(DefaultCacheLockingManager.java:64)
    	at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver.resolve(CacheLockingArtifactDependencyResolver.java:39)
    	at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolve(DefaultConfigurationResolver.java:91)
    	at org.gradle.api.internal.artifacts.ivyservice.SelfResolvingDependencyConfigurationResolver.resolve(SelfResolvingDependencyConfigurationResolver.java:40)
    	at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolve(ShortCircuitEmptyConfigurationResolver.java:52)
    	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolve(ErrorHandlingConfigurationResolver.java:43)
    	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:359)
    	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveNow(DefaultConfiguration.java:334)
    	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:327)
    	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
    	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:642)
    	... 74 more
    Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: No cached version of com.mojang:realms:1.10.19 available for offline mode.
    	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.StartParameterResolutionOverride$FailedRemoteAccess.resolveComponentMetaData(StartParameterResolutionOverride.java:111)
    	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$ResolveAndCacheRepositoryAccess.resolveComponentMetaData(CachingModuleComponentRepository.java:297)
    	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.BaseModuleComponentRepositoryAccess.resolveComponentMetaData(BaseModuleComponentRepositoryAccess.java:42)
    	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedModuleComponentRepository$CachedAccess.resolveComponentMetaData(InMemoryCachedModuleComponentRepository.java:75)
    	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.resolveComponentMetaData(ErrorHandlingModuleComponentRepository.java:89)
    	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ComponentMetaDataResolveState.process(ComponentMetaDataResolveState.java:66)
    	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ComponentMetaDataResolveState.resolve(ComponentMetaDataResolveState.java:58)
    	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.findBestMatch(RepositoryChainComponentMetaDataResolver.java:116)
    	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.findBestMatch(RepositoryChainComponentMetaDataResolver.java:99)
    	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolveModule(RepositoryChainComponentMetaDataResolver.java:72)
    	... 106 more

    BUILD FAILED

    Total time: 14.797 secs

</details>

**Comment by Pokechu22** [comment]
The realms library is a dependency of the game, found at `https://libraries.minecraft.net/com/mojang/realms/1.10.19/realms-1.10.19.jar`.  It's very similar to authlib and the narrator library (both are hosted only on libraries.minecraft.net).  _Technically_ it isn't needed to run the game, only for realms stuff, but the version JSON still references it.

What's interesting about them is that these libraries are updated after the version releases.  When 1.12.2 first released, it used a different version (as far as I can tell, 1.10.17) than it does now; you can sort of see a version history [on mojira](https://bugs.mojang.com/projects/REALMS?selectedItem=com.atlassian.jira.jira-projects-plugin:release-page&status=released-unreleased) which says that PC-1.10.19 was released on 15/Feb/18 and before that 1.10.18 was the latest.

That said, I'm not sure how FG knows that the realms library needs to be updated even in offline mode.  This is just an explanation as to why there is a new version of the realms library.

**Comment by Pokechu22** [comment]
I see that the `getVersionJson` task was run, even though you're in offline mode.  That's probably how it knew to update it...  but that doesn't explain the inconsistency with it sometimes working and sometimes not working.

**Comment by radfast** [comment]
that's making sense - my build 138 was the first build after 15/Feb/18.

Seems like two mysteries remain:

1)  Why is it running the ```getVersionJson``` task in offline mode?

2)  How did it work in my build 139?  (Maybe this time because ```getVersionJson``` didn't find a different realms version so the "offline" code didn't check whether realms was really the latest?)

**Comment by Pokechu22** [comment]
It looks like the `getVersionJson` task [doesn't break the build if it errors](https://github.com/MinecraftForge/ForgeGradle/blob/f49079dd11c037f74cc740285b2c5504fbf8a7f6/src/main/java/net/minecraftforge/gradle/common/BasePlugin.java#L415).  Maybe you were actually completely offline during build 139 so the task errored and was skipped?  Can you post the log for it?

As for why it still runs: it uses [this code](https://github.com/MinecraftForge/ForgeGradle/blob/550f88c357d6a33510839233ca1f70e3e49a77f3/src/main/java/net/minecraftforge/gradle/tasks/EtagDownloadTask.java) which just seems to not know not to run in offline mode.

**Comment by radfast** [comment]
<details>
<summary>Build 139 log</summary>

    ./gradlew build packCoreJarDev packPlanetsJarDev packMicCoreJarDev packApi cleanOldJarDev --stacktrace --offline
    This mapping 'snapshot_20171003' was designed for MC 1.12! Use at your own peril.
    #################################################
             ForgeGradle 2.3-SNAPSHOT-315a0db        
      https://github.com/MinecraftForge/ForgeGradle  
    #################################################
                   Powered by MCP unknown               
                 http://modcoderpack.com             
             by: Searge, ProfMobius, Fesh0r,         
             R4wk, ZeuX, IngisKahn, bspkrs           
    #################################################
    Found AccessTransformer: micdoodlecore_at.cfg
    :deobfCompileDummyTask
    :getVersionJson
    :extractUserdev UP-TO-DATE
    :downloadClient SKIPPED
    :downloadServer SKIPPED
    :splitServerJar SKIPPED
    :mergeJars SKIPPED
    :applyBinaryPatches SKIPPED
    :deobfProvidedDummyTask
    :extractDependencyATs SKIPPED
    :extractMcpData SKIPPED
    :extractMcpMappings SKIPPED
    :genSrgs SKIPPED
    :deobfMcMCP SKIPPED
    :sourceApiJava UP-TO-DATE
    :compileApiJava UP-TO-DATE
    :processApiResources UP-TO-DATE
    :apiClasses UP-TO-DATE
    :sourceMainJava UP-TO-DATE
    :compileJavaNote: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.

    :processResources
    :classes
    :jar
    :sourceTestJava UP-TO-DATE
    :compileTestJava UP-TO-DATE
    :processTestResources UP-TO-DATE
    :testClasses UP-TO-DATE
    :test UP-TO-DATE
    :reobfJar
    :extractAnnotationsJar
    :assemble
    :check UP-TO-DATE
    :build
    :packCoreJarDev
    :packPlanetsJarDev
    :packMicCoreJarDev
    :packApi
    :cleanOldJarDev

    BUILD SUCCESSFUL

    Total time: 46.881 secs

    This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.7/userguide/gradle_daemon.html
    + cd ..
    Archiving artifacts
    IRC notifier plugin: Sending notification to: #galacticraft
    IRC notifier plugin: [ERROR] not connected. Cannot send message to '#galacticraft'
    Finished: SUCCESS

</details>

This built OK, produced 4 working `.jar` files.

I don't think the Jenkins was offline at any time - it's on a remote server and I couldn't have accessed it to initiate the build if it was offline... ...

**Comment by radfast** [comment]
Anyhow, don't want to waste your time chasing down the mystery of why it **did** work in 139.

Is there any possibility of fixing the `EtagDownloadTask` so that it doesn't run in offline mode?  No big deal, but I do feel safer if I can always build my code in offline mode.

**Comment by Pokechu22** [comment]
Hm, yeah, no obvious error message in there making it look like the task failed (though I have [seen travis error](https://travis-ci.org/audacity/audacity/builds/345530279) due to offline stuff).

I'll look into fixing `EtagDownloadTask`.  That said... for CI specifically, wouldn't you want to do a clean build from scratch each time?  I'd think it'd be more useful to make sure that it builds correctly for all uses on a fresh checkout.

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
