### ISSUE TITLE
Cannot setup 1.7.10-forge1614 decompWorkspace

### ISSUE THREAD

**Issue by 351768593** [MinecraftForge/ForgeGradle#506]
**I downloaded the latest src file, and tried to setup the decompWorkspace run with `gradlew.bat setupDecompWorkspace -Dhttps.proxyHost=12
7.0.0.1 -Dhttp.proxyHost=127.0.0.1 -Dhttps.proxyPort=1080 -Dhttp.proxyPort=1080 -Dorg.gradle.jvmargs=-Xms2000m --info ` ( you can ignore the proxy settings)
but it always failed with exception**

**how to fix this?**

**here is more information**

D:\OneDrive\MinecraftForgeSRC\forge-1.7.10-10.13.4.1614-1.7.10-src>gradlew.bat setupDecompWorkspace -Dhttps.proxyHost=12
7.0.0.1 -Dhttp.proxyHost=127.0.0.1 -Dhttps.proxyPort=1080 -Dhttp.proxyPort=1080 -Dorg.gradle.jvmargs=-Xms2000m --info --
stacktrace
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: http://gradle.org/
docs/2.0/userguide/gradle_daemon.html.
Starting Gradle daemon
Starting daemon process: workingDir = C:\Users\a3517\.gradle\daemon\2.0, daemonArgs: [C:\Program Files\Java\jdk1.8.0_121
\bin\java.exe, -Xms2000m, -Dfile.encoding=GBK, -cp, C:\Users\a3517\.gradle\wrapper\dists\gradle-2.0-bin\5h57m9vra0mjv9qs
45oqtsb5c0\gradle-2.0\lib\gradle-launcher-2.0.jar, org.gradle.launcher.daemon.bootstrap.GradleDaemon, 2.0, C:\Users\a351
7\.gradle\daemon, 120000, 79449938-2dee-499e-a478-3db5c4342c8e, -Xms2000m, -Dfile.encoding=GBK]
Starting process 'Gradle build daemon'. Working directory: C:\Users\a3517\.gradle\daemon\2.0 Command: C:\Program Files\J
ava\jdk1.8.0_121\bin\java.exe -Xms2000m -Dfile.encoding=GBK -cp C:\Users\a3517\.gradle\wrapper\dists\gradle-2.0-bin\5h57
m9vra0mjv9qs45oqtsb5c0\gradle-2.0\lib\gradle-launcher-2.0.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 2.0 C:\U
sers\a3517\.gradle\daemon 120000 79449938-2dee-499e-a478-3db5c4342c8e -Xms2000m -Dfile.encoding=GBK
Successfully started process 'Gradle build daemon'
An attempt to start the daemon took 4.348 secs.
Connected to the daemon. Dispatching BuildAndStop{id=f9e358a3-0fcf-443d-ac00-cdbab2bd14ef.1, currentDir=D:\OneDrive\Mine
craftForgeSRC\forge-1.7.10-10.13.4.1614-1.7.10-src} request.
The client will now receive all logging from the daemon (pid: 16280). The daemon log file: C:\Users\a3517\.gradle\daemon
\2.0\daemon-16280.out.log
Executing build with daemon context: DefaultDaemonContext[uid=79449938-2dee-499e-a478-3db5c4342c8e,javaHome=C:\Program F
iles\Java\jdk1.8.0_121,daemonRegistryDir=C:\Users\a3517\.gradle\daemon,pid=16280,idleTimeout=120000,daemonOpts=-Xms2000m
,-Dfile.encoding=GBK]
Starting Build
Settings evaluated using empty settings script.
Projects loaded. Root project using build file 'D:\OneDrive\MinecraftForgeSRC\forge-1.7.10-10.13.4.1614-1.7.10-src\build
.gradle'.
Included projects: [root project 'forge-1.7.10-10.13.4.1614-1.7.10-src']
Evaluating root project 'forge-1.7.10-10.13.4.1614-1.7.10-src' using build file 'D:\OneDrive\MinecraftForgeSRC\forge-1.7
.10-10.13.4.1614-1.7.10-src\build.gradle'.

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\OneDrive\MinecraftForgeSRC\forge-1.7.10-10.13.4.1614-1.7.10-src\build.gradle' line: 18

* What went wrong:
A problem occurred evaluating root project 'forge-1.7.10-10.13.4.1614-1.7.10-src'.
> java.io.EOFException: End of input at line 32732 column 3

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'forge-1.7.10-10.13.4.1614-1.7.10-src'.

        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory
.java:54)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:18
7)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.j
ava:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:470)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:79)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:31)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:128)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:105)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:85)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter
.java:81)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:39)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:45)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:35)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:24)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
        at org.gradle.launcher.daemon.server.exec.StartStopIfBuildAndStop.execute(StartStopIfBuildAndStop.java:33)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
        at org.gradle.launcher.daemon.server.exec.ReturnResult.execute(ReturnResult.java:34)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:71)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:69)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:69)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:45)

        at org.gradle.launcher.daemon.server.DaemonStateCoordinator.runCommand(DaemonStateCoordinator.java:184)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy.doBuild(StartBuildOrRespondWithBusy.java:4
9)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
        at org.gradle.launcher.daemon.server.exec.HandleStop.execute(HandleStop.java:30)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
        at org.gradle.launcher.daemon.server.exec.DaemonHygieneAction.execute(DaemonHygieneAction.java:39)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
        at org.gradle.launcher.daemon.server.exec.CatchAndForwardDaemonFailure.execute(CatchAndForwardDaemonFailure.java
:32)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
        at org.gradle.launcher.daemon.server.exec.DefaultDaemonCommandExecuter.executeCommand(DefaultDaemonCommandExecut
er.java:51)
        at org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler$ConnectionWorker.handleCommand(DefaultInco
mingConnectionHandler.java:155)
        at org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler$ConnectionWorker.receiveAndHandleCommand(D
efaultIncomingConnectionHandler.java:128)
        at org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler$ConnectionWorker.run(DefaultIncomingConnec
tionHandler.java:116)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java
:64)
Caused by: com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 32732 column 3
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at com.google.gson.Gson.fromJson(Gson.java:768)
        at com.google.gson.Gson.fromJson(Gson.java:717)
        at com.google.gson.Gson.fromJson(Gson.java:689)
        at net.minecraftforge.gradle.user.patch.UserPatchBasePlugin.setVersionInfoJson(UserPatchBasePlugin.java:145)
        at net.minecraftforge.gradle.user.patch.UserPatchBasePlugin.applyPlugin(UserPatchBasePlugin.java:46)
        at net.minecraftforge.gradle.common.BasePlugin.apply(BasePlugin.java:154)
        at net.minecraftforge.gradle.common.BasePlugin.apply(BasePlugin.java:49)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:110)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:69)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:35)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction
.java:117)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.
java:36)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:
85)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.jav
a:130)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:41)
        at org.gradle.api.Project$apply$0.call(Unknown Source)
        at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
        at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
        at build_2maaknkamuh5fdmijsqbdpg08b.run(D:\OneDrive\MinecraftForgeSRC\forge-1.7.10-10.13.4.1614-1.7.10-src\build
.gradle:18)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory
.java:52)
        ... 53 more
Caused by: java.io.EOFException: End of input at line 32732 column 3
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1377)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:456)
        at com.google.gson.stream.JsonReader.skipValue(JsonReader.java:1209)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:170
)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172
)
        at com.google.gson.Gson.fromJson(Gson.java:803)
        ... 73 more

BUILD FAILED

Total time: 23.432 secs

**Comment by braddevans** [comment]
there is an error in the build.gradle could you send a copy of your build.gradle to check for the issue?

**Comment by FirokOtaku** [comment]
> there is an error in the build.gradle could you send a copy of your build.gradle to check for the issue?
> 
> on line 18 is :
> 
> ```java
> apply plugin: 'forge'
> ```
> 
> are you using java 8?

I was using the default build.gradle downloaded from `files.minecraftforge.net` without making any changes.
I followed the steps of the documentation`https://mcforge.readthedocs.io/en/latest/gettingstarted/#terminal-free-intellij-idea-configuration`
Yes, I'm using java8, and the ide is IntelliJ IDEA.

Actually, after 40-hours trying now my workspace has successfully been set up, though I still dont know what happened.
It seems all the things get running after I changed the "gradle wrapper" setting to "Use default gradle wrapper".
Maybe there's some conflicts between forge gradle and offical gradle on my pc.

**Comment by jriwanek** [comment]
ForgeGradle uses Gradle, for 1.7.10, you can use 2.14-~4.4.1, if you're using newer than 4.4.1 for 1.7.10 it will NOT work.

**Comment by LexManos** [comment]
Use the forums.

**Comment by FirokOtaku** [comment]
> ForgeGradle uses Gradle, for 1.7.10, you can use 2.14-~4.4.1, if you're using newer than 4.4.1 for 1.7.10 it will NOT work.

Ohh, that might be the point. The offical gradle I have is 4.8.
Maybe you should remind us to pay attention in documentation, there are so many people meet the same problem.


> Use the forums.

On this problem, forum has not provided any help. Every answer is in the same word:  "you should run cleanCache" or "redownload the mdk", even "you should uninstall java8"


Anyway, thank you so much, guys!
