### ISSUE TITLE
[1.12] setupDecompWorkspace fails when a debug MC instance is started in another project

### ISSUE THREAD

**Issue by WeAthFoLD** [MinecraftForge/ForgeGradle#527]
I have 2 different mod projects in same computer. When I open the MC instance on project A (whose environment is already setup), and then try to `gradle setupDecompWorkspace` on projectB, the `extractNatives` task failed with the error message below:

```
> Task :extractNatives FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':extractNatives'.
> Could not expand ZIP 'C:\Users\WeAthFolD\.gradle\caches\modules-2\files-2.1\org.lwjgl.lwjgl\lwjgl-platform\2.9.4-nightly-20150209\b84d5102b9dbfabfeb5e43c7e2828d98a7fc80e0\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar'.
```

Using `--debug` shows:
```
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.api.GradleException: Could not expand ZIP 'C:\Users\WeAthFolD\.gradle\caches\modules-2\files-2.1\org.lwjgl.lwjgl\lwjgl-platform\2.9.4-nightly-20150209\b84d5102b9dbfabfeb5e43c7e2828d98a7fc80e0\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar'.
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:104)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.file.collections.FileTreeAdapter.visit(FileTreeAdapter.java:117)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at net.minecraftforge.gradle.tasks.ExtractConfigTask.doTask(ExtractConfigTask.java:80)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:786)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:753)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 31 more
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.api.GradleException: Could not copy zip entry C:\Users\WeAthFolD\.gradle\caches\modules-2\files-2.1\org.lwjgl.lwjgl\lwjgl-platform\2.9.4-nightly-20150209\b84d5102b9dbfabfeb5e43c7e2828d98a7fc80e0\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar!OpenAL64.dll to 'C:\Users\WeAthFolD\.gradle\caches\minecraft\net\minecraft\natives\1.12.2\OpenAL64.dll'.
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.file.AbstractFileTreeElement.copyTo(AbstractFileTreeElement.java:79)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at net.minecraftforge.gradle.util.ExtractionVisitor.visitFile(ExtractionVisitor.java:62)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:97)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 47 more
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.io.FileNotFoundException: C:\Users\WeAthFolD\.gradle\caches\minecraft\net\minecraft\natives\1.12.2\OpenAL64.dll (The process cannot access the file because it is being used by another process)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.file.AbstractFileTreeElement.copyFile(AbstractFileTreeElement.java:91)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.file.AbstractFileTreeElement.copyTo(AbstractFileTreeElement.java:74)
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 49 more
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger]
23:35:08.846 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 2m 49s
```

It's apparent that the file is locked by the running MC instance, therefore the ZIP 'failed' to unarchive. I think it's better to check if the files are already there before unzipping the archive file.

System: Windows 10

**Comment by DaemonUmbra** [comment]
This is FG 2.3, correct?

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
