### ISSUE TITLE
[FG3] Crash with gradle 4.10 and higher

### ISSUE THREAD

**Issue by Janrupf** [MinecraftForge/ForgeGradle#552]
Trying to apply forgegradle 3.0.90 fails with gradle 4.10 and higher. The problem itself is caused by https://github.com/amadornes/Artifactural. However, I'm reporting here as the repository seems inactive.
Looks like that in Gradle 4.10 a constructor was removed:
```
java.lang.NoSuchMethodError: org.gradle.api.internal.artifacts.repositories.AbstractArtifactRepository: method <init>()V not found
        at com.amadornes.artifactural.gradle.GradleRepositoryAdapter.<init>(GradleRepositoryAdapter.java:99)
        at com.amadornes.artifactural.gradle.GradleRepositoryAdapter.add(GradleRepositoryAdapter.java:88)
        at net.minecraftforge.gradle.common.util.BaseRepo$Builder.attach(BaseRepo.java:122)
        at net.minecraftforge.gradle.userdev.UserDevPlugin.lambda$apply$8(UserDevPlugin.java:178)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1$1.run(DefaultListenerBuildOperationDecorator.java:155)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:58)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:152)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction.execute(DefaultListenerBuildOperationDecorator.java:149)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
```
(Stacktrace shortened to exclude unrelevant parts)

**Comment by LexManos** [comment]
This is know, but a far lower priority then everything else.
The fix needs to be on Artifactual's side.
It needs to update, and have a major version bump.
Then we need to bump FG's version when we bump the AF dep.
BUT we're more focused on getting all the other things done.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/Artifactural/commit/747c582804bdcd0409417fdd92f7a3042d80b6b5
