### ISSUE TITLE
Running any IntelliJ configuration causes ClassCastException

### ISSUE THREAD

**Issue by burdoto** [MinecraftForge/ForgeGradle#568]
When trying to run any testing configuration with module '.main' selected, this error occurrs:
```
2019-03-03 13:36:02,855 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2019-03-03 13:36:02,857 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by GradleStart (file:/C:/Users/Kaleidox/.gradle/caches/minecraft/net/minecraftforge/forge/1.10.2-12.18.3.2185/start/) to field java.lang.ClassLoader.sys_paths
WARNING: Please consider reporting this to the maintainers of GradleStart
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[13:36:02] [main/INFO] [GradleStart]: Extra: []
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraftforge.gradle.GradleForgeHacks.searchCoremods(GradleForgeHacks.java:87)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:86)
	at GradleStart.main(GradleStart.java:26)

Process finished with exit code 1
```

**Comment by burdoto** [comment]
The problem was that I had the JDK 11 selected as the project JDK.
