### ISSUE TITLE
error when running gradlew setupDevWorkspace IDE

### ISSUE THREAD

**Issue by zeetronn** [MinecraftForge/ForgeGradle#698]
log : 
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at org.gradle.wrapper.Install.unzip(Install.java:215)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:75)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by TheCurle** [comment]
setupDevWorkspace is only used in old, unsupported versions.
These old, unsupported versions are not supported.
Update.

**Comment by zeetronn** [comment]
same happens with gradlew genIntellijRuns

**Comment by TheCurle** [comment]
Again, old and unsupported.

**Comment by zeetronn** [comment]
aight i am on jdk 8u231 and ide 2019 1.1

**Comment by TheCurle** [comment]
No support means, you won't get any help here. This is not an issue *if you update to a modern version*

**Comment by zeetronn** [comment]
thanks dude i am updating to the latest vers sorry for annoying ya
