### ISSUE TITLE
flutter issue

### ISSUE THREAD

**Issue by ujjwaltandon** [MinecraftForge/ForgeGradle#723]
please help me with this ..previous issues on git hub didnt helped me ...

Exception in thread "main" java.lang.RuntimeException: Could not determine wrapper version.
	at org.gradle.wrapper.GradleWrapperMain.wrapperVersion(GradleWrapperMain.java:111)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.RuntimeException: No build receipt resource found.
	at org.gradle.wrapper.GradleWrapperMain.wrapperVersion(GradleWrapperMain.java:97)
	... 1 more
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by DaemonUmbra** [comment]
Looking like you took a piece of the wrapper but not all of it.
