### ISSUE TITLE
FG4 crash when trying to setup official mappings

### ISSUE THREAD

**Issue by Nightenom** [MinecraftForge/ForgeGradle#740]
Hello,
I was trying to setup official mappings using fg4 and fresh new mdk with these changes in `build.gradle` and `gradle\wrapper\gradle-wrapper.properties`:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-6.8-bin.zip
classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '4.+', changing: true
mappings channel: 'official', version: '1.16.5'
minecraft 'net.minecraftforge:forge:1.16.5-36.0.1'
```
Works flawlessly with fg3 and gradle 4.10.3, with using of fg3 generated files fg4 works too

#### below is extraction of crash log: https://gist.github.com/Nightenom/3c4c45f7d397234e26b25209f0c7f7b2
```
gradlew command: gradlew clean cleanEclipse eclipse genVSCodeRuns
Java: 11.0.8 JVM: 11.0.8+10(AdoptOpenJDK) Arch: amd64
New Dep: net.minecraftforge:forge:1.16.5-36.0.1_mapped_official_1.16.5

Task :createSrgToMcp
java.nio.file.NoSuchFileException: P:\apps\common\gradle-cache\caches\forge_gradle\mcp_repo\de\oceanlabs\mcp\mcp_config\1.16.5\mcp_config-1.16.5-obf_to_srg.tsrg
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:219)
        at java.base/java.nio.file.Files.newBufferedWriter(Files.java:2919)
        at java.base/java.nio.file.Files.newBufferedWriter(Files.java:2962)
        at net.minecraftforge.srgutils.MappingFile.write(MappingFile.java:133)
        at net.minecraftforge.gradle.mcp.MCPRepo.findRenames(MCPRepo.java:353)
        at net.minecraftforge.gradle.mcp.MCPRepo.findOfficialMapping(MCPRepo.java:462)
        at net.minecraftforge.gradle.mcp.MCPRepo.findNames(MCPRepo.java:368)
        at net.minecraftforge.gradle.mcp.MCPRepo.findFile(MCPRepo.java:175)
        at net.minecraftforge.gradle.common.util.BaseRepo.getArtifact(BaseRepo.java:81)
        at net.minecraftforge.gradle.common.util.BaseRepo.getArtifact(BaseRepo.java:41)
        at net.minecraftforge.gradle.common.util.BaseRepo$Builder$1.lambda$getArtifact$0(BaseRepo.java:127)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
        at net.minecraftforge.gradle.common.util.BaseRepo$Builder$1.getArtifact(BaseRepo.java:127)
        at net.minecraftforge.gradle.common.util.BaseRepo$Builder$1.getArtifact(BaseRepo.java:124)
        at net.minecraftforge.artifactural.base.repository.ArtifactProviderBuilder$Complete.getArtifact(ArtifactProviderBuilder.java:92)
        at net.minecraftforge.artifactural.base.repository.SimpleRepository.getArtifact(SimpleRepository.java:41)
        at net.minecraftforge.artifactural.gradle.GradleRepositoryAdapter.getArtifact(GradleRepositoryAdapter.java:326)
        at net.minecraftforge.gradle.common.util.MavenArtifactDownloader._generate(MavenArtifactDownloader.java:136)
        at net.minecraftforge.gradle.common.util.MavenArtifactDownloader._download(MavenArtifactDownloader.java:115)
        at net.minecraftforge.gradle.common.util.MavenArtifactDownloader.generate(MavenArtifactDownloader.java:83)
        at net.minecraftforge.gradle.mcp.task.GenerateSRG.findNames(GenerateSRG.java:79)
        at net.minecraftforge.gradle.mcp.task.GenerateSRG.apply(GenerateSRG.java:49)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        continues with gradle only classes
```

**Comment by Cyborgmas** [comment]
Seems to come from a discrepancy here:
https://github.com/MinecraftForge/ForgeGradle/commit/f7f2eaf62988dc6b574ebd9f978095aab3578383#diff-d9231f0ab14d22dba1a095646914059cd783bb0d6251764602cccdd11044a2bdL210-L221

vs

https://github.com/MinecraftForge/SrgUtils/blob/master/src/main/java/net/minecraftforge/srgutils/MappingFile.java#L133-L138

**Comment by josephtarbit** [comment]
I get the same exception with MCP mappings, only happens in 4.0.3, seems to work in 4.0.1 (unsure about 4.0.2).

**Comment by Cyborgmas** [comment]
the commit i linked is 4.02 normally so below that is fine
