### ISSUE TITLE
Forge Gradle Certificate Expiration

### ISSUE THREAD

**Issue by IStrikeboomI** [MinecraftForge/ForgeGradle#817]
Whenever I try to run Forge Gradle I get this error
```
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Fri Jul 30 18:59:38 CDT 2021
	at sun.security.x509.CertificateValidity.valid(CertificateValidity.java:277)
	at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:677)
	at sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
	at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
	... 141 more
```
It seems that the url https://www.abrarsyed.com/ForgeGradleVersion.json had its certificate expired on July 30 and needs to be renewed to work properly

**Comment by DaemonUmbra** [comment]
That is not an active page, if you MUST list ForgeGradle versions you can do so through Forge's maven using standard maven practices.
