### ISSUE TITLE
How to fix this error on Intelij idea

### ISSUE THREAD

**Issue by f4r2** [MinecraftForge/ForgeGradle#820]
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraftforge.gradle.GradleForgeHacks.searchCoremods(GradleForgeHacks.java:87)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:86)
	at GradleStart.main(GradleStart.java:26)

Im using java 16

**Comment by SizableShrimp** [comment]
This issue tracker is not for tech support.
