### ISSUE TITLE
[FG6] `reobfJar` fails when Mixin writes an empty tsrg file

### ISSUE THREAD

**Issue by SquidDev** [MinecraftForge/ForgeGradle#919]
Sometimes it's possible to have Mixin configured on a project but have it write an empty `xxx-mappings.tsrg` file. In this case, the `reobfJar` task will fail due to an out-of-bounds in srgutils:

```
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at net.minecraftforge.srgutils.InternalUtils.loadNamed(InternalUtils.java:39)
        at net.minecraftforge.srgutils.InternalUtils.load(InternalUtils.java:28)
        at net.minecraftforge.srgutils.IMappingFile.load(IMappingFile.java:27)
        at net.minecraftforge.srgutils.IMappingFile.load(IMappingFile.java:22)
        at net.minecraftforge.gradle.userdev.tasks.RenameJarInPlace.apply(RenameJarInPlace.java:66)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

## Reproduction steps
 - Download the MDK and convert it to use ForgeGradle 6.
 - Add the Mixin Gradle plugin, and set up MixinGradle with the following:
   ```groovy
   dependencies { annotationProcessor("org.spongepowered:mixin:0.8.5:processor") }
   mixin { add(sourceSets.main, "examplemod.refmap.json") }
   ```
   Note no mixin configs are configured.
 - Run `./gradlew reobfJar`. The build should fail as `build/tmp/compileJava/compileJava-mappings.tsrg` is empty.

**Comment by SquidDev** [comment]
Thank you!
